name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image
      run: docker build -t my-spring-boot-app .

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <your-aws-account-id>.dkr.ecr.us-west-2.amazonaws.com

    - name: Push Docker image to ECR
      run: |
        docker tag my-spring-boot-app:latest <your-aws-account-id>.dkr.ecr.us-west-2.amazonaws.com/my-spring-boot-app:latest
        docker push <your-aws-account-id>.dkr.ecr.us-west-2.amazonaws.com/my-spring-boot-app:latest

    - name: Deploy to EKS
      run: |
        aws eks update-kubeconfig --name my-cluster --region us-west-2
        helm upgrade --install my-spring-boot-app ./my-spring-boot-app

